# Change these first
owner: lakejason0 # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: 存档计划（MediaWiki）
    url: https://lakeus.xyz
  - name: Lake桑的存档馆（WordPress.com）
    url: https://lakejason0.wordpress.com
  - name: 静态主页（Static）
    url: https://lakejason0.ml
  - name: Lake桑的存档馆（GitHub.io）
    url: https://lakejason0.github.io
  - name: 湖远星的Miraheze试验场
    url: https://lakeus.miraheze.org
  - name: 存档计划（Wiki.js）（未启用）
    url: $SECRET_SITE

assignees:
  - lakejason0

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.lakejason0.ml
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://lakeus.xyz/images/6/6f/Logo.svg
  name: 存档计划 - 服务状态
  introTitle: "欢迎来到 Project Archive Service Status。"
  introMessage: 您可以在这个第三方服务中查看我所有 Web 服务的运作情况。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: 返回存档计划（MediaWiki）
      href: https://lakeus.xyz

i18n:
  activeIncidents: 活跃事件
  incidentReport: "#$NUMBER 号事件报告 →"
  activeIncidentSummary: 开始于 $DATE · 有 $POSTS 则跟进
  incidentTitle: "#$NUMBER 号事件细节"
  incidentDetails: 事件细节
  incidentFixed: 已修复
  incidentOngoing: 持续中
  incidentOpenedAt: 开始于
  incidentClosedAt: 结束于
  incidentSubscribe: 关注跟进
  incidentViewOnGitHub: 在 GitHub 上查看
  incidentCommentSummary: $DATE · $AUTHOR
  incidentBack: ← 返回至所有事件
  pastIncidents: 过去的事件
  pastIncidentsResolved: 解决时间 $MINUTES 分钟 · $POSTS 则跟进
  liveStatus: 实时状态
  overallUptime: "总计在线时间：$UPTIME"
  overallUptimeTitle: 总计在线时间
  averageResponseTime: "平均延迟：$TIMEms"
  averageResponseTimeTitle: 平均延迟
  sevelDayResponseTime: 延迟时间（7 天）图表
  responseTimeMs: 延迟时间（毫秒）
  ms: ms
  loading: 加载中
  navGitHub: GitHub
  footer: 本页面[开放源代码]($REPO) · 由 [Upptime](https://upptime.js.org) 提供支持
  rateLimitExceededTitle: 已超过速率限制
  rateLimitExceededIntro: 您已经超过了这个小时可以发送的请求的限制。因此，在您再次访问本网站前，您需要等待。或者，您也可以添加一个 GitHub Personal Access Token（GitHub 个人访问密钥）来继续使用本网站。
  rateLimitExceededWhatDoesErrorMean: 这个错误是什么意思？
  rateLimitExceededErrorMeaning: 本网站使用 GitHub API 来访问我们的网站的实时状态数据。GitHub 默认允许每一个 IP 地址每小时发送 60 个请求，然而您已经超过了这个限制。
  rateLimitExceededErrorHowCanFix: 如何修复？
  rateLimitExceededErrorFix: 您可以再等待一个小时。这样，您的 IP 地址的限制就会恢复正常。或者，您也可以添加一个 GitHub Personal Access Token（GitHub 个人访问密钥），这样可以放宽您的限制到 5000 次。
  rateLimitExceededGeneratePAT: 了解如何添加 GitHub Personal Access Token（GitHub 个人访问密钥）
  rateLimitExceededHasSet: GitHub Personal Access Token（GitHub 个人访问密钥）已设置。
  rateLimitExceededRemoveToken: 移除密钥
  rateLimitExceededGitHubPAT: GitHub Personal Access Token（GitHub 个人访问密钥）
  rateLimitExceededCopyPastePAT: 复制粘贴您的密钥
  rateLimitExceededSaveToken: 保存密钥
  errorTitle: 错误
  errorIntro: 尝试拉取最新的状态细节时发生了错误。
  errorText: 请稍后再试。
  errorHome: 带我回家
  url: "URL"
  status: "状态"
  history: "历史"
  responseTime: "延迟时间"
  up: "🟩 正常"
  degraded: "🟨 出现问题"
  down: "🟥 下线"
  responseTimeGraphAlt: "延迟时间图表"
  responseTimeDay: "24小时延迟时间"
  responseTimeWeek: "7天延迟时间"
  responseTimeMonth: "30天延迟时间"
  responseTimeYear: "1年延迟时间"
  uptime: "全时段在线时间"
  uptimeDay: "24小时在线时间"
  uptimeWeek: "7天在线时间"
  uptimeMonth: "30天在线时间"
  uptimeYear: "1年在线时间"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "所有系统均正常"
  degradedPerformance: "🟨 性能降级"
  completeOutage: "🟥 服务完全中断"
  partialOutage: "🟧 服务部分中断"
  duration24H: 24小时
  duration7D: 7天
  duration30D: 30天
  duration1Y: 1年
  durationAll: 全时段
  pastScheduledMaintenance: 过去计划的维护
  scheduledMaintenance: 已计划的维护
  scheduledMaintenanceSummaryStarted: 开始于$DATE，持续$DURATION分钟
  scheduledMaintenanceSummaryStarts: 开始于$DATE，持续$DURATION分钟
  startedAt: 开始于
  startsAt: 开始于
  duration: 持续时间
  durationMin: $DURATION 分钟
  incidentCompleted: 已完成
  incidentScheduled: 已计划

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
